name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  pull-requests: write

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: reviewdog/action-shellcheck@5ebd09ddbe2ebb471646ce234c6c8dd18663ca7c # v1.30.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: ${{ steps.reporter.outputs.value }}
          level: warning

  # hadolint:
  #   name: runner / hadolint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: haya14busa/action-cond@v1
  #       id: reporter
  #       with:
  #         cond: ${{ github.event_name == 'pull_request' }}
  #         if_true: "github-pr-review"
  #         if_false: "github-check"
  #     - uses: reviewdog/action-hadolint@v1
  #       with:
  #         github_token: ${{ secrets.github_token }}
  #         reporter: ${{ steps.reporter.outputs.value }}
  #         level: warning

  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-misspell@9daa94af4357dddb6fd3775de806bc0a8e98d3e4 # v1.26.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
          locale: "US"

  alex:
    name: runner / alex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-alex@6083b8ca333981fa617c6828c5d8fb21b13d916b # v1.16.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
